on:
  create:
    tags:
      - v*
name: Build and Release apk
jobs:
  calculadora_imc:
    name: Build APK calculadora_imc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: cd calculadora_imc && flutter pub get
    - run: cd calculadora_imc && flutter build apk --release
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "calculadora_imc/build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
  contador_de_pessoas:
    name: Build APK contador_de_pessoas
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: cd contador_de_pessoas && flutter pub get
    - run: cd contador_de_pessoas && flutter build apk --release
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "contador_de_pessoas/build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
  conversor_moeda:
    name: Build APK conversor_moeda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: cd conversor_moeda && flutter pub get
    - run: cd conversor_moeda && flutter build apk --release
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "conversor_moeda/build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
